<?php

use App\Service\Item;

/** @var Item[] $items */
$items = $this->items;

/** @var string $path */
$path = $this->workingPath;
?>

<script>currentPath = '<?php echo $path; ?>';</script>

<div class="mt-3 py-2 px-3 border rounded-5 bg-body-tertiary">
  <?php echo $this->partial('common/breadcrumbs'); ?>
</div>

<div class="row mt-3 align-items-stretch" data-item-selectable>
  <?php foreach ($items as $item) : ?>
    <?php if (!$item->isFile()) : ?>
      <div class="col-2 mb-3" data-item-selectable-item>
        <?php echo $this->partial('index/folder', ['folder' => $item]); ?>
      </div>
    <?php endif; ?>
  <?php endforeach; ?>
  <div class="col-12"></div>
  <?php foreach ($items as $item) : ?>
    <?php if ($item->isFile()) : ?>
      <div class="col-1 mb-3" data-item-selectable-item>
        <?php echo $this->partial('index/file', ['file' => $item]); ?>
      </div>
    <?php endif; ?>
  <?php endforeach; ?>
</div>

<template data-admin-contextmenu-remove-all-template>
  <ul class="dropdown-menu position-absolute top-0 left-0 m-0 shadow-5-strong" data-admin-contextmenu-remove-all>
    <li>
      <a class="dropdown-item" role="button" onclick="removeSelected()">
        <i class="fas fa-trash me-1"></i> <?php echo \App\Service\Locale::t('Remove selected?'); ?>
      </a>
    </li>
    <li>
      <hr class="dropdown-divider mt-0"/>
    </li>
    <li class="px-2 pb-2">
      <div class="d-flex justify-content-between small">
        <div class="text-muted"><?php echo \App\Service\Locale::t('Size'); ?>:</div>
        <div class="text-muted fw-bold" data-admin-contextmenu-remove-all-size></div>
      </div>
    </li>
  </ul>
</template>