<?php

use App\Service\Item;

/** @var Item[] $items */
$items = $this->items;
?>
<?php if (count($items)) : ?>
  <div class="mt-4">
    <div class="row gx-3 d-flex align-items-stretch">
      <?php foreach ($items as $item) : ?>
        <?php if (!$item->isFile()) : ?>
          <div class="col-2 mb-3">
            <?php echo $this->partial('index/folder', ['folder' => $item]); ?>
          </div>
        <?php endif; ?>
      <?php endforeach; ?>
    </div>
  </div>
  <div class="mt-4">
    <div class="row gx-3 d-flex align-items-stretch">
      <?php foreach ($items as $item) : ?>
        <?php if ($item->isFile()) : ?>
          <div class="col-2 mb-3">
            <?php echo $this->partial('index/file', ['file' => $item]); ?>
          </div>
        <?php endif; ?>
      <?php endforeach; ?>
    </div>
  </div>
<?php endif; ?>