<?php

use App\Service\Item;

/** @var Item $folder */
$folder = $this->folder;
?>
<div class="modal-body">
  <div class="w-100 d-flex">
    <div class="text-warning me-3">
      <i class="fas fa-folder fa-5x"></i>
    </div>
    <div>
      <h3><?php echo $folder->name; ?></h3>
      <span class="badge badge-primary mt-2 text-start">
        Time: <?php echo date('d-m-y H:i', $folder->time); ?>
      </span>
    </div>
  </div>
</div>
<div class="modal-footer">
  <button type="button"
          class="btn btn-danger"
          onclick="removeFolder('<?php echo $folder->path; ?>', true)"
          data-mdb-ripple-init>
    <?php echo \App\Service\Locale::t('Remove?'); ?>
  </button>
  <button type="button"
          class="btn btn-primary"
          data-mdb-dismiss="modal"
          data-mdb-ripple-init>
    <?php echo \App\Service\Locale::t('No'); ?>
  </button>
</div>
